/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { AppProvider, useApp } from './context/AppContext';
import { PayPalScriptProvider } from '@paypal/react-paypal-js';
import { ThemeProvider } from './context/ThemeContext';
import { Navbar } from './components/Navbar';
import { Footer } from './components/Footer';
import { Home } from './components/pages/Home';
import { ProductDetail } from './components/pages/Product';
import { BoutiqueCart } from './components/pages/Cart';
import { Checkout } from './components/pages/Checkout';
import { UserDashboard } from './components/pages/UserDashboard';
import { AdminDashboard } from './components/pages/AdminDashboard';
import { Auth } from './components/pages/Auth';
import { Wishlist } from './components/pages/Wishlist';
import { 
  ShieldAlert, 
  Database, 
  Globe, 
  Lock, 
  Server, 
  Wifi, 
  AlertTriangle, 
  XCircle, 
  CheckCircle2, 
  RefreshCcw,
  Activity
} from 'lucide-react';

// Inner App with active view rendering and transition wrapper
const AppContent: React.FC = () => {
  const { activeView, user, setActiveView, toastMessage } = useApp();
  const [isDbHealthy, setIsDbHealthy] = useState<boolean | null>(null);
  const [isRetrying, setIsRetrying] = useState<boolean>(false);
  const [dbError, setDbError] = useState<{
    message: string;
    name?: string;
    code?: string;
    diagnosticExplanation: string;
    checks: {
      uriValidity: 'valid' | 'invalid' | 'unknown';
      atlasNetworkAccess: string;
      userCredentials: string;
      mongooseStatus: string;
      dnsResolution: string;
      atlasConnectivity: string;
    };
  } | null>(null);

  const fetchHealthState = (forceReconnect = false) => {
    return fetch(forceReconnect ? '/api/health?reconnect=true' : '/api/health')
      .then((res) => {
        if (!res.ok) throw new Error('Health check API responded with an error');
        return res.json();
      })
      .then((data) => {
        const healthy = data.database === 'connected';
        setIsDbHealthy(healthy);
        if (data.error) {
          setDbError(data.error);
        } else if (!healthy) {
          setDbError({
            message: "Mongoose failed connection select handshake.",
            name: "MongooseServerSelectionError",
            diagnosticExplanation: "The database configuration took too long to select an active MongoDB Atlas cluster node. This generally occurs because Atlas is refusing connections from the dynamic IP addresses generated by your workspace container.",
            checks: {
              uriValidity: 'valid',
              atlasNetworkAccess: "❌ BLOCKED. Atlas blocked connection from this dynamic sandbox container IP address.",
              userCredentials: "⚠️ UNVERIFIED. Connection blocked before verification step could execute.",
              mongooseStatus: "Disconnected (readyState = 0)",
              dnsResolution: "✅ ACTIVE. resolved primary MongoDB Atlas host definitions safely.",
              atlasConnectivity: "❌ BLOCKED. Handshake dropped at Atlas core router layer."
            }
          });
        } else {
          setDbError(null);
        }
      })
      .catch((err) => {
        setIsDbHealthy(false);
        setDbError({
          message: err.message || String(err),
          name: "APIRequestFailure",
          diagnosticExplanation: "Unable to query server status. The database initialization process may have crashed the server, or the dev container is currently starting up.",
          checks: {
            uriValidity: 'unknown',
            atlasNetworkAccess: "❌ UNREACHABLE. Request timed out.",
            userCredentials: "❌ UNREACHABLE. Server failed to answer.",
            mongooseStatus: "Mongoose status unreadable",
            dnsResolution: "❌ UNKNOWN. Local sandbox connection failed.",
            atlasConnectivity: "❌ OFFLINE. Cannot query Atlas cluster states."
          }
        });
      });
  };

  useEffect(() => {
    fetchHealthState();
    
    const params = new URLSearchParams(window.location.search);
    const viewParam = params.get('view');
    if (viewParam === 'admin-dashboard') {
      setActiveView('admin-dashboard');
    } else if (viewParam === 'user-dashboard') {
      setActiveView('user-dashboard');
    }
  }, []);

  const handleManualRetry = () => {
    setIsRetrying(true);
    fetchHealthState(true).finally(() => {
      setTimeout(() => setIsRetrying(false), 1200);
    });
  };

  const renderActiveView = () => {
    switch (activeView) {
      case 'home':
        return <Home />;
      case 'product':
        return <ProductDetail />;
      case 'cart':
        return <BoutiqueCart />;
        
      case 'checkout':
        return <Checkout />;
        
      case 'wishlist':
        return <Wishlist />;
        
      case 'user-dashboard':
        // Protected route check: Must be signed in
        if (!user) {
          return <Auth onSuccessRedirect="user-dashboard" />;
        }
        return <UserDashboard />;
        
      case 'admin-dashboard':
        // Protected route check: Sign-in validation
        if (!user) {
          return <Auth onSuccessRedirect="admin-dashboard" />;
        }
        // Protected route check: Admin role authorization checking
        if (user.role !== 'admin') {
          return (
            <div className="flex justify-center items-center py-20 px-4">
              <div className="w-full max-w-md text-center rounded-3xl border border-red-200 bg-red-50/40 p-8 dark:border-red-950/20 dark:bg-zinc-950/40 backdrop-blur-md">
                <ShieldAlert className="h-12 w-12 text-red-500 mx-auto animate-pulse" />
                <h3 className="mt-4 font-serif text-lg font-bold text-slate-900 dark:text-white">Admin Clearance Required</h3>
                <p className="mt-2 text-xs text-slate-500 leading-relaxed dark:text-zinc-400 font-sans">
                  The active customer account "<strong>{user.name}</strong>" does not have administrative roles required to log into the MORVEX admin console.
                </p>
                <div className="mt-6 flex flex-col space-y-2 font-mono">
                  <button
                    onClick={() => setActiveView('user-dashboard')}
                    className="rounded-2xl bg-zinc-950 px-4 py-2.5 text-xs font-bold text-white hover:bg-zinc-850 dark:bg-white dark:text-zinc-950 dark:hover:bg-zinc-100 cursor-pointer"
                  >
                    View My Account Dashboard
                  </button>
                  <button
                    onClick={() => setActiveView('home')}
                    className="text-xs text-gray-500 hover:text-gray-950 dark:text-zinc-550 dark:hover:text-white py-1.5 rounded-lg border border-transparent hover:border-gray-200 dark:hover:border-zinc-900"
                  >
                    Return to Shop Homepage
                  </button>
                </div>
              </div>
            </div>
          );
        }
        return <AdminDashboard />;
        
      case 'auth':
        return <Auth />;
      default:
        return <Home />;
    }
  };

  return (
    <div className="min-h-screen flex flex-col bg-[#f4f4f4] text-slate-900 transition-colors duration-300 dark:bg-zinc-950 dark:text-zinc-50 font-sans">
      
      {/* Navigation Layer */}
      <Navbar />

      {/* Database Connection Warning Alert Banner - Detailed Dashboard View when fails */}
      {isDbHealthy === false ? (
        <div className="flex-grow flex items-center justify-center p-4 sm:p-8">
          <div className="w-full max-w-4xl rounded-3xl border border-red-200/50 bg-white p-6 sm:p-8 shadow-2xl dark:border-red-950/40 dark:bg-zinc-900/60 backdrop-blur-xl animate-fade-in space-y-6">
            
            {/* Header Alert Label */}
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-b border-gray-100 pb-5 dark:border-zinc-850">
              <div className="flex items-center space-x-3.5">
                <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-red-100 text-red-600 dark:bg-red-950/40 dark:text-red-400">
                  <AlertTriangle className="h-6 w-6 animate-pulse" />
                </div>
                <div>
                  <h2 className="font-serif text-lg font-bold text-slate-900 dark:text-white tracking-tight">
                    MongoDB Server Selection Failure
                  </h2>
                  <p className="text-[10px] uppercase font-mono tracking-wider text-red-500 font-bold mt-0.5">
                    Offline Demo Fallbacks Disabled • Connection Required
                  </p>
                </div>
              </div>
              <button
                onClick={handleManualRetry}
                disabled={isRetrying}
                className="inline-flex items-center justify-center space-x-2 rounded-2xl bg-zinc-950 px-4 py-2.5 text-xs font-bold text-white hover:bg-zinc-850 dark:bg-white dark:text-zinc-950 dark:hover:bg-zinc-100 disabled:opacity-50 cursor-pointer transition-all shrink-0"
              >
                <RefreshCcw className={`h-3.5 w-3.5 ${isRetrying ? 'animate-spin' : ''}`} />
                <span>{isRetrying ? 'Verifying socket connection...' : 'Test Connection Status'}</span>
              </button>
            </div>

            {/* Diagnostic Columns */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              
              {/* Left Column: Exact Raw Error Logger */}
              <div className="space-y-4">
                <div className="flex items-center space-x-1.5 text-slate-500 dark:text-zinc-400">
                  <Activity className="h-4 w-4" />
                  <span className="text-[10px] font-mono uppercase tracking-wider font-bold">Trace Logger (Raw Exception Mongoose)</span>
                </div>
                <div className="rounded-2xl bg-zinc-950 p-4 text-xs font-mono text-red-400 border border-zinc-850 max-h-[160px] overflow-y-auto leading-relaxed shadow-inner">
                  <div className="text-[10px] text-zinc-550 border-b border-zinc-850 pb-1.5 mb-2 font-mono uppercase tracking-wide">
                    {dbError?.name || "MongooseServerSelectionError"} ({dbError?.code || "HANDSHAKE_TIMEOUT"})
                  </div>
                  <div>
                    {dbError?.message || "Could not connect to any servers in your MongoDB Atlas cluster. Mongoose ServerSelection handshake timed out."}
                  </div>
                </div>
                
                {/* Clean Reason Explainer */}
                <div className="rounded-2xl bg-gray-50 p-4 dark:bg-zinc-900/30 border border-gray-100 dark:border-zinc-850">
                  <h4 className="text-[10px] font-mono uppercase tracking-wider text-slate-500 dark:text-zinc-500 font-bold mb-1.5 flex items-center space-x-1">
                    <span>Diagnostic Explanation & Cause</span>
                  </h4>
                  <p className="text-xs text-slate-650 leading-relaxed dark:text-zinc-400 font-sans">
                    {dbError?.diagnosticExplanation || "Verify if MongoDB services are online, credentials matched perfectly inside .env file environment configs and network socket allows inbound entries."}
                  </p>
                </div>
              </div>

              {/* Right Column: Required Check Points Matching Check List */}
              <div className="space-y-4 text-xs font-sans">
                <div className="flex items-center space-x-1.5 text-slate-500 dark:text-zinc-400">
                  <Database className="h-4 w-4" />
                  <span className="text-[10px] font-mono uppercase tracking-wider font-bold">Atlas Diagnostic Checkpoints</span>
                </div>
                
                <div className="grid grid-cols-1 gap-2.5">
                  
                  {/* checkpoint 1 */}
                  <div className="p-3 rounded-2xl border border-gray-100 bg-gray-50/50 dark:border-zinc-850 dark:bg-zinc-900/20 flex items-start space-x-2.5">
                    <CheckCircle2 className={`h-4 w-4 shrink-0 mt-0.5 ${dbError?.checks.uriValidity === 'invalid' ? 'text-red-500' : 'text-emerald-500'}`} />
                    <div className="space-y-0.5">
                      <p className="font-mono text-[9px] uppercase tracking-wide text-slate-400 dark:text-zinc-550">1. MONGODB_URI validity</p>
                      <p className="text-[11px] font-bold text-slate-850 dark:text-zinc-300">
                        {dbError?.checks.uriValidity === 'invalid' ? "⚠️ Invalid String: Check cluster format spelling" : "✅ Formatted Cleanly: Connection URL parser validated"}
                      </p>
                    </div>
                  </div>

                  {/* checkpoint 2 */}
                  <div className="p-3 rounded-2xl border border-gray-100 bg-gray-50/50 dark:border-zinc-850 dark:bg-zinc-900/20 flex items-start space-x-2.5">
                    <Globe className="h-4 w-4 text-amber-500 mt-0.5 shrink-0" />
                    <div className="space-y-0.5">
                      <p className="font-mono text-[9px] uppercase tracking-wide text-slate-400 dark:text-zinc-550">2. DNS Resolution</p>
                      <p className="text-[11px] text-slate-800 dark:text-zinc-300 leading-relaxed font-sans">
                        {dbError?.checks.dnsResolution || "Testing lookup..."}
                      </p>
                    </div>
                  </div>

                  {/* checkpoint 3 */}
                  <div className="p-3 rounded-2xl border border-gray-100 bg-gray-50/50 dark:border-zinc-850 dark:bg-zinc-900/20 flex items-start space-x-2.5">
                    <Lock className="h-4 w-4 text-amber-500 mt-0.5 shrink-0" />
                    <div className="space-y-0.5">
                      <p className="font-mono text-[9px] uppercase tracking-wide text-slate-400 dark:text-zinc-550">3. Database User Credentials</p>
                      <p className="text-[11px] text-slate-800 dark:text-zinc-300 leading-relaxed font-sans">
                        {dbError?.checks.userCredentials || "Pending authorization checks..."}
                      </p>
                    </div>
                  </div>

                  {/* checkpoint 4 */}
                  <div className="p-3 rounded-2xl border border-gray-100 bg-gray-50/50 dark:border-zinc-850 dark:bg-zinc-900/20 flex items-start space-x-2.5">
                    <Server className="h-4 w-4 text-amber-500 mt-0.5 shrink-0" />
                    <div className="space-y-0.5">
                      <p className="font-mono text-[9px] uppercase tracking-wide text-slate-400 dark:text-zinc-550">4. Mongoose Connection Status</p>
                      <p className="text-[11px] text-slate-800 dark:text-zinc-300 leading-relaxed font-sans font-mono font-medium">
                        {dbError?.checks.mongooseStatus || "Connecting state..."}
                      </p>
                    </div>
                  </div>

                  {/* checkpoint 5 */}
                  <div className="p-3 rounded-2xl border border-gray-100 bg-gray-50/50 dark:border-zinc-850 dark:bg-zinc-900/20 flex items-start space-x-2.5">
                    <Wifi className="h-4 w-4 text-red-500 mt-0.5 shrink-0 animate-pulse" />
                    <div className="space-y-0.5">
                      <p className="font-mono text-[9px] uppercase tracking-wide text-slate-400 dark:text-zinc-550">5. Atlas Network Access (IP Whitelisting)</p>
                      <p className="text-[11px] text-amber-600 dark:text-amber-400 leading-relaxed font-sans">
                        {dbError?.checks.atlasNetworkAccess || "Checking egress barriers..."}
                      </p>
                    </div>
                  </div>

                  {/* checkpoint 6 */}
                  <div className="p-3 rounded-2xl border border-gray-100 bg-gray-50/50 dark:border-zinc-850 dark:bg-zinc-900/20 flex items-start space-x-2.5">
                    <XCircle className="h-4 w-4 text-red-500 mt-0.5 shrink-0" />
                    <div className="space-y-0.5">
                      <p className="font-mono text-[9px] uppercase tracking-wide text-slate-400 dark:text-zinc-550">6. MongoDB Atlas Connectivity</p>
                      <p className="text-[11px] text-slate-800 dark:text-zinc-300 leading-relaxed font-sans">
                        {dbError?.checks.atlasConnectivity || "Connecting handshake..."}
                      </p>
                    </div>
                  </div>

                </div>
              </div>

            </div>

            {/* Quick Action Guide */}
            <div className="p-4 bg-red-50/40 rounded-2xl border border-red-100 text-xs text-red-800 dark:bg-red-950/10 dark:border-red-950/20 dark:text-red-400 leading-relaxed font-sans">
              <strong>💡 QUICK ACTION TO ESTABLISH CONNECTION:</strong> Open your MongoDB Atlas Console, click <strong>"Network Access"</strong> under the Security menu, and select <strong>"+ Add IP Address"</strong>. Add IP Address <code>0.0.0.0/0</code> with title <strong>"Permit Cloud Run Ingress/Egress"</strong>. Click confirm. Wait 1 min for the status to switch to Active, then click the retry button above.
            </div>

          </div>
        </div>
      ) : (
        <>
          {/* Main Content Area */}
          <main className="flex-grow mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8 py-8 animate-fade-in">
            <div id="route-transition-container">
              {renderActiveView()}
            </div>
          </main>
        </>
      )}

      {/* Footer Level */}
      <Footer />

      {/* App-Wide Toast Notification */}
      {toastMessage && (
        <div className="fixed top-24 right-4 sm:right-8 z-50 flex items-center space-x-2 rounded-lg bg-zinc-900 px-4 py-3 text-sm font-semibold text-white shadow-xl dark:bg-white dark:text-zinc-950 animate-fade-in">
          <span>{toastMessage}</span>
        </div>
      )}
    </div>
  );
};

export default function App() {
  const [paypalClientId, setPaypalClientId] = useState<string | null>(null);

  useEffect(() => {
    fetch('/api/paypal/config')
      .then(r => r.json())
      .then(d => setPaypalClientId(d.clientId || 'test'))
      .catch(() => setPaypalClientId('test'));
  }, []);

  if (!paypalClientId) return null;

  return (
    <PayPalScriptProvider options={{ clientId: paypalClientId, currency: "USD", intent: "capture" }}>
      <ThemeProvider>
        <AppProvider>
          <AppContent />
        </AppProvider>
      </ThemeProvider>
    </PayPalScriptProvider>
  );
}
